baseurl = 'https://carlahy.github.io/zwemkunst/'
languageCode = 'en-us'
title = 'zwemkunst'
theme= 'hugo-theme-console'


[params]
  # Cutting off the page title to two chars for mobile
  # titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "zwemkunst/"
  url = "zwemkunst/"

  [[params.navlinks]]
  name = "lavanderiasdelmundo/"
  url = "lavanderiasdelmundo/"
  
  [[params.navlinks]]
  name = "photos/"
  url = "photos/"
